version: "3.8"

services:
    fast-api:
        build: .
        ports:
            - "8000:80"
        volumes:
            - .:/code
        command: >
            sh -c "uvicorn main:app --host 0.0.0.0 --port 80"
